# Generated by Django 2.2.3 on 2019-07-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proctor_name', models.CharField(max_length=150)),
                ('proctor_about', models.CharField(max_length=300)),
                ('proctor_contact', models.IntegerField()),
                ('proctor_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_contact', models.IntegerField()),
                ('student_address', models.TextField()),
                ('student_interest', models.TextField()),
                ('student_extracurricular', models.TextField()),
                ('student_image', models.ImageField(upload_to='')),
                ('student_sem1', models.IntegerField()),
                ('student_sem2', models.IntegerField()),
                ('student_sem3', models.IntegerField()),
                ('student_sem4', models.IntegerField()),
                ('student_sem5', models.IntegerField()),
                ('student_sem6', models.IntegerField()),
                ('proctor_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='src.Proctor')),
            ],
        ),
    ]
