# Generated by Django 2.2a1 on 2019-08-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='proctor',
            name='proc_department',
            field=models.ForeignKey(default=69, on_delete=django.db.models.deletion.CASCADE, to='src.Department'),
            preserve_default=False,
        ),
    ]
