# Generated by Django 2.2a1 on 2019-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem_pointer',
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_sem6',
            field=models.IntegerField(default=0),
        ),
    ]
