# Generated by Django 2.2a1 on 2019-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20190810_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_sem1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sem2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sem3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sem4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sem5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_sem6',
            field=models.FloatField(default=0),
        ),
    ]
