# Generated by Django 2.2.4 on 2019-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
